### ISSUE TITLE
Can't import or create a valid FASTA AA file

### ISSUE THREAD

**Issue by craftjk** [TeselaGen/das#35]
_From @mfero on October 18, 2015 5:29_

Can't import or create a valid FASTA AA file. Should be able to create in a simple text box editor for direct typing or cut/paste.
>gi|129295|sp|P01013|OVAX_CHICK GENE X PROTEIN (OVALBUMIN-RELATED) QIKDLLVSSSTDLDTTLVLVNAIYFKGMWKTAFNAEDTREMPFHVTKQESKPVQMMCMNNSFNVAT PAEKMKILELPFASGDLSMLVLLPDEVSDLERIE TINFEKLTEWTNPNTMEKRRVKVYLPQMKIEEK NLTSVLMALGMTDLFIPSANLTGISSAESLKISQ VHGAFMELSEDGIEMAGSTGVIEDIKHSPESEQ RADHPFLFLIKHNPTNTIVYFGRYWSP

_Copied from original issue: TeselaGen/ve#1438_

**Comment by mfero** [comment]
we don't want this hanging over us, lets get if fixed now.

**Comment by mfero** [comment]
Protein genbank files are being read as sequence files. The parser should be able to tell the difference.  Now that the parsers are being split out (good idea!) we can automate tests with an extensive library of different types of examples of AA and DNA fasta and genbank files :) Good task for the intern :) I'll create a new ticket to that effect, since we don't want this ticket to be a long progression of edge cases.

**Comment by njhillson** [comment]
Failing. If I attempt to re-import the same amino acid sequences twice, I get "Import Error: Servor Error". I should instead get a duplicated sequence warning/error as happens through DNA sequence import.

**Comment by tnrich** [comment]
I believe Nathan's issue should now be fixed.

**Comment by mfero** [comment]
![image](https://cloud.githubusercontent.com/assets/7561861/11732007/d616a240-9f54-11e5-83b4-fcbf110ec6fc.png)

**Comment by tnrich** [comment]
Hey Mike, this pull request hasn't been merged in yet. Sorry about the
miscommunication. I'll move it back a stage.

**Comment by mfero** [comment]
looking good.

**Comment by craftjk** [comment]
This issue was moved to TeselaGen/ve#1761
